version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: movies
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $SECURITY_USER_NAME
      MYSQL_ROOT_PASSWORD: $SECURITY_USER_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      SECURITY_USER_NAME: $SECURITY_USER_NAME
      SECURITY_USER_PASSWORD: $SECURITY_USER_PASSWORD
    depends_on:
      - db

volumes:
  db_data: